FPS = 60

BACKGROUND_MUSIC = 'song.wav'


BACKGROUND_COLOR = '#00000055'


BALL_INVINCIBILITY_TIME = 1
BALL_MIN_SPEED = 500
BALL_MAX_SPEED = 800
BALL_ACCELERATION = 500

BALL_RADIUS = 10

BALL_COLOR = "#0ff"
BALL_INVINCIBLE_COLOR = "#88C"


STRING_STRENGTH = 10000

CANON_RADIUS = 20

CANON_COOLDOWN = 3

CANON_ALERT_TIME = 0.6

CANON_COLOR_1 = "#888"
CANON_COLOR_2 = "#AAA"
CANON_ALERT_COLOR = "#F00"

CANON_SPAWN_COOLDOWN = 1.5
CANON_SPAWN_MIN_DISTANCE = 200


MISSILE_RADIUS = 10

MISSILE_INITIAL_SPEED = 60

MISSILE_ROTATION_SPEED = 100 / 180 * Math.PI // in radians per second
MISSILE_ACCELERATION = 40

MISSILE_COLOR = "#CCC"


PARTICLE_LIFETIME = 0.1
// not a friction actually, but a factor of speed reduction per frame
PARTICLE_FRICTION = Math.pow(0.2, (1 / FPS)) // friction per frame
FIRE_COLORS = ["#F00", "#FA0"]


BONUS_COLOR = BALL_INVINCIBLE_COLOR
BONUS_RADIUS = 7
BONUS_SPAWN_COOLDOWN = 8
BONUS_SPAWN_MIN_DISTANCE = 300
