FPS = 60

BACKGROUND_MUSIC = 'song.wav'


BACKGROUND_COLOR = '#00000033'


BALL_INVINCIBILITY_TIME = 1
BALL_MIN_SPEED = 500
BALL_MAX_SPEED = 800
BALL_ACCELERATION = 500

BALL_RADIUS = 10

BALL_COLOR = "#0ff"
BALL_INVINCIBLE_COLOR = "#88C"

BALL_TRAIL_DENSITY = 50 // particles per second
BALL_TRAIL_PARTICLE_SPEED = 4
BALL_TRAIL_PARTICLE_LIFETIME = 0.7

STRING_STRENGTH = 10000


ENEMY_COLOR_1 = "#888"
ENEMY_COLOR_2 = "#AAA"


RAILGUN_RADIUS = 25
RAILGUN_COOLDOWN = 7
RAILGUN_ROTATION_SPEED = 40 / 180 * Math.PI // in radians per second

RAILGUN_AIM_TIME = 2 // time of showing the aim line
RAILGUN_SHOOT_TIME = 1.5 // included in cooldown, time when the railgun is not rotating

RAILGUN_LASER_COLOR = "#F00"

RAILGUN_SPAWN_COOLDOWN = 10
RAILGUN_SPAWN_MIN_DISTANCE = 400

RAILGUN_LASER_LIFETIME = 0.1

RAILGUN_AIM_PARTICLES_DENSITY = 0.1 // particles per unit of length per second
RAILGUN_LASER_PARTICLES_AMOUNT = 1 // particles per unit of length per shot

RAILGUN_AIM_PARTICLES_WIDTH = 10
RAILGUN_LASER_PARTICLES_WIDTH = 50


CANON_RADIUS = 20
CANON_COOLDOWN = 3
CANON_ROTATION_SPEED = Infinity

CANON_ALERT_TIME = 0.6

CANON_ALERT_COLOR = "#F00"

CANON_SPAWN_COOLDOWN = 1.5
CANON_SPAWN_MIN_DISTANCE = 200


MISSILE_RADIUS = 10

MISSILE_INITIAL_SPEED = 60

MISSILE_ROTATION_SPEED = 100 / 180 * Math.PI // in radians per second
MISSILE_ACCELERATION = 40

MISSILE_COLOR = "#CCC"


PARTICLE_LIFETIME = 0.1
// not a friction actually, but a factor of speed reduction per frame
PARTICLE_FRICTION = Math.pow(0.2, (1 / FPS)) // friction per frame
FIRE_COLORS = ["#F00", "#FA0"]


BONUS_COLOR = BALL_INVINCIBLE_COLOR
BONUS_RADIUS = 7
BONUS_SPAWN_COOLDOWN = 8
BONUS_SPAWN_MIN_DISTANCE = 300


DESTROY_SOURCE_ADDITIONAL_COLORS = {
    "ball": [BALL_INVINCIBLE_COLOR],
    "railgunLaser": [RAILGUN_LASER_COLOR],
}
